### PR TITLE
Corrected an omission in the long description.

### PR DESCRIPTION
**Pull request by drgrigg**
The previous description mentions 'Richard' without explaining who he is. Added in a few words to make that clear.

### CODE REVIEW

**Review by acabal — CHANGES_REQUESTED** [review]
Thanks David. Once more thing I noticed, can you use double quotes for "wards of Chancery" and move the comma inside the quotes? I must have missed that during the initial review.

Lastly make sure to run prepare-release again so that the version number/updated date gets bumped. Thanks!

**Comment by drgrigg** [comment]
Changes done.

**Comment by drgrigg** [comment]
Sorry, forgot to run prepare-release!

**Comment by drgrigg** [comment]
Done it now. Should be OK to go.

**Comment by acabal** [comment]
Great, thanks!

**Pull request merged**
